### ISSUE TITLE
-V doesn't work

### ISSUE THREAD

**Issue by ronsawyer777** [ricardobranco777/clean_registry#2]
if you run clean_registry -V you don't get the version but rather the usage because a container or volume isn't found.  This works better:

if args.help:
        print('usage: ' + usage)
        sys.exit(0)
    elif args.version:
        print(progname + " " + VERSION)
        sys.exit(0)
    elif not agrs.container_or_volume:
        print('usage:" + usage)
        sys.exit(1)

**Comment by ricardobranco777** [comment]
Fixed. Thanks!
