### ISSUE TITLE
Script's exit code 1?

### ISSUE THREAD

**Issue by sprnza** [ricardobranco777/clean_registry#6]
Hi there! Thanks for the project. What's a point to set the script's exit code to 1?

```
        exit_status = 0
        for image in images:
            if not clean_repo(image):
                exit_status = 1

        if not self.garbage_collect():
           exit_status = 1
```
Or do I use it incorrectly? I suppose that in order to delete an image I must run this script twice:
firstly to remove references using 
```
docker run --rm --volumes-from 46068a8a3483  -v /var/run/docker.sock:/var/run/docker.sock  ricardobranco/clean_registry -x 46068a8a3483 <repo>:<tag>
```
 and then to garbage-collect the second time:
```
docker run --rm --volumes-from 46068a8a3483  -v /var/run/docker.sock:/var/run/docker.sock  ricardobranco/clean_registry 46068a8a3483
```
In both cases I get 1 exit code returned for me. Is it correct?

**Comment by ricardobranco777** [comment]
Hi @sprnza 

The script is supposed to be run only once.  Do you have the error messages?

**Comment by sprnza** [comment]
Nope I don't have any error. Actually just after filling the issue, I've started to play with the script and found out that if I don't suppress output with `-q` the exit code is always 1 if I use `-q` the exit code is 0.

**Comment by sprnza** [comment]
So to be sure: in order to delete an image I should run `-x <repo>:<tag>`? But in what cases I might need to run the script without `-x` then?

**Comment by ricardobranco777** [comment]
@sprnza 
When you push different images with the same `<repo>:<tag>`  (as usually happens with `latest`) you have dangling images.  By default (without the `-x` flag), you remove those dangling images.  The `-x` flag is used when you also want to remove the whole `<repo>:<tag>` reference (which includes the current image).

**Comment by sprnza** [comment]
Aha! Cool! Thanks! But what about the exit code? Does it work as intended?

**Comment by ricardobranco777** [comment]
@sprnza 
Is there anything I could improve in the documentation to clearly state the use of the `-x` flag?

I don't know why you're getting that exit status when args.quiet (`-q` option) is set.  The exit status works as intended to flag that some repo or tag didn't exist.  It wouldn't be a bad idead to refactor the code to have this check at the very beginning and yell and exit.   But I don't feel this is ok right now until I invest some time to create some tests and add them to Travis.

**Comment by sprnza** [comment]
I'm not sure if I could advice about the documentation improvements because I think that my question's arisen because of my lack of knowledge in docker garbage-collection. 

Regarding the exit code: as far as I understand `if not self.garbage_collect():` will always be true, when garbage_collect() returns 0 (which is an exit code of `registry garbage-collect` command). So the exit_code is being set to 1. I'm not sure why it's not happening when I use `-q` arg though.

**Comment by ricardobranco777** [comment]
@sprnza Can you please re-test it?  I pushed a new image to Docker Hub.  Thanks!

**Comment by sprnza** [comment]
Yep, fixed! Thank you a lot!
