### ISSUE TITLE
linkname '/bin/busybox' not found

### ISSUE THREAD

**Issue by biscaldis** [ricardobranco777/clean_registry#8]
I'm running in Docker and having this issue. The container exit with a `KeyError Exception`.

`Docker version 19.03.5, build 633a0ea838`

Registry image details
```
"id": "sha256:708bc6af7e5e539bdb59707bbf1053cc2166622f5e1b17666f0ba5829ca6aaea",
"RepoTags": ["registry:2", "registry:2.7.1", "registry:2.7", "registry:latest"],
"RepoDigests":["registry@sha256:7d081088e4bfd632a88e3f3bcd9e007ef44a796fddfe3261407a3f9f04abe1e7"],
```

Full Exception Traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/clean_registry.py", line 360, in <module>
    main()
  File "/usr/local/bin/clean_registry.py", line 353, in main
    cleaner = RegistryCleaner(container=args.container_or_volume)
  File "/usr/local/bin/clean_registry.py", line 185, in __init__
    self.registry_dir = self.get_registry_dir()
  File "/usr/local/bin/clean_registry.py", line 243, in get_registry_dir
    data = yaml.load(self.get_file(config_yml), Loader=yaml.FullLoader)
  File "/usr/local/bin/clean_registry.py", line 222, in get_file
    as tar, tar.extractfile(os.path.basename(path)) \
  File "/usr/lib/python3.6/tarfile.py", line 2092, in extractfile
    return self.extractfile(self._find_link_target(tarinfo))
  File "/usr/lib/python3.6/tarfile.py", line 2388, in _find_link_target
    raise KeyError("linkname %r not found" % linkname)
KeyError: "linkname '/bin/busybox' not found"
```

**Comment by ricardobranco777** [comment]
Can you please provide a way to reproduce this?  The full command line used would be helpful, as well as the contents of the config.yml if you modified it.

While taking a look at this, I fixed another unrelated bug.  It didn't support fixed Docker Registry versions.

**Comment by biscaldis** [comment]
> While taking a look at this, I fixed another unrelated bug. It didn't support fixed Docker Registry versions.

Thanks, this indeed was another issue I wanted to rise. But I fixed that with a workaround, running the registry with the generic v2 tag. 

Command I ran
`docker run --rm --volumes-from portus_registry_1 -v /var/run/docker.sock:/var/run/docker.sock ricardobranco/clean_registry portus_registry_1`

Registry configuration `config.yml`
```
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001

```

**Comment by biscaldis** [comment]
Any update on this?

**Comment by ricardobranco777** [comment]
> Any update on this?

Hi.  I couldn't reproduce it in a simple environment and haven't had the time to set up a Portus Registry.  

Can you please provide a minimal way to reproduce it?

**Comment by biscaldis** [comment]
Yes, I do. I am attaching the docker-registry project which allows you to deploy a full Portus environment. Read the README.md to understand how to briefly configure it, don't mind LDAP configuration, it's not needed. 

[docker-registry.zip](https://github.com/ricardobranco777/clean_registry/files/4614317/docker-registry.zip)

**Comment by ricardobranco777** [comment]
> Yes, I do. I am attaching the docker-registry project which allows you to deploy a full Portus environment. Read the README.md to understand how to briefly configure it, don't mind LDAP configuration, it's not needed.
> 
> [docker-registry.zip](https://github.com/ricardobranco777/clean_registry/files/4614317/docker-registry.zip)

Can you please provide a minimal & faster way to reproduce it, without me having to parse the README, remove the LDAP stuff from the YAML, setting variables, etc?  It would be easier to have those steps in a shell script.  I mean, I only need to quickly setup the environment (ideally, with one single command) and test the registry cleaner as I don't really have much time to understand the deployment.  If you do that I promise to sort it out ASAP.

**Comment by ricardobranco777** [comment]
Any news?
